FROM golang:buster

RUN apt-get update && \
    apt-get install nano iputils-ping telnet net-tools ifstat -y

RUN cp  /usr/share/zoneinfo/Asia/Shanghai /etc/localtime  && \
    echo 'Asia/Shanghai'  > /etc/timezone

WORKDIR $GOPATH/src/github.com/yomorun/yomo-cluing-shake
COPY go.mod go.sum ./sink/main.go .
COPY ./sink/asset ./sink/asset
RUN GOPROXY="https://goproxy.cn" GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o ./shake-sink ./main.go

EXPOSE 8000

CMD ["./shake-sink"]
