FROM golang:buster

RUN apt-get update && \
    apt-get install nano iputils-ping telnet net-tools ifstat -y

RUN cp  /usr/share/zoneinfo/Asia/Shanghai /etc/localtime  && \
    echo 'Asia/Shanghai'  > /etc/timezone

WORKDIR $GOPATH/src/github.com/yomorun/yomo-cluing-shake
COPY go.mod go.sum .
COPY ./cmd/emitter  ./cmd/emitter
RUN go get -d -v ./...

CMD ["sh", "-c", "go run ./cmd/emitter/main.go"]
